site_name: PHP - Kurs
theme: readthedocs
use_directory_urls: false
repo_url: https://github.com/efiku/php-kurs
site_description: Nowoczesny kurs programowania w PHP!
site_author: Marek Woś & Krzysztof Pazdur

pages:
- Strona Główna: 'index.md'
- Autorzy: 'authors.md'
